apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-webapp-deploy
  name: go-webapp-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-webapp-deploy
  type: NodePort